management:
  # info: management 바로 아래서 시작
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  # 액츄에이터 보안을 위해 엔드 포인트 포트 변경 9292
  server:
    port: 8080
  # 활성화
  endpoint:
    shutdown:
      enabled: true
    health:
  #    show-components: always
        show-details: always
  endpoints:
  # 노출
    web:
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: jeu

# default: info
logging:
  level:
    hello.controller: debug

# tomcat metrics 활성화
server:
  tomcat:
    mbeanregistry:
      enabled: true
